# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\booking.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowx(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(618, 759)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: \"#60ACE0\"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(140, 120, 331, 191))
        self.calendar.setStyleSheet("font: 8pt \"Myanmar Text\";\n"
"background-color: \"#60ACE9\";")
        self.calendar.setObjectName("calendar")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setGeometry(QtCore.QRect(140, 320, 331, 241))
        self.gridWidget.setStyleSheet("border: 1px solid white;\n"
"border radius: 5px;\n"
"padding: 10px;\n"
"padding-left: 20px;\n"
"color: white; \n"
"font-weight: bolder; \n"
"background-color:\"#329CE3\";")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.greater70 = QtWidgets.QLabel(self.gridWidget)
        self.greater70.setStyleSheet("font: 9pt \"Candara\";\n"
"border: none; \n"
"")
        self.greater70.setObjectName("greater70")
        self.gridLayout.addWidget(self.greater70, 3, 0, 1, 1)
        self.nPeople = QtWidgets.QLabel(self.gridWidget)
        self.nPeople.setStyleSheet("font: 9pt \"Candara\";\n"
"border: none;\n"
"font-weigth: bold; \n"
"")
        self.nPeople.setObjectName("nPeople")
        self.gridLayout.addWidget(self.nPeople, 2, 0, 1, 1)
        self.numPiscinasLabel = QtWidgets.QLabel(self.gridWidget)
        self.numPiscinasLabel.setStyleSheet("border: none; ")
        self.numPiscinasLabel.setObjectName("numPiscinasLabel")
        self.gridLayout.addWidget(self.numPiscinasLabel, 5, 0, 1, 1)
        self.entryHour = QtWidgets.QLabel(self.gridWidget)
        self.entryHour.setStyleSheet("\n"
"font: 9pt \"Candara\";\n"
"border: none;\n"
"")
        self.entryHour.setObjectName("entryHour")
        self.gridLayout.addWidget(self.entryHour, 1, 0, 1, 1)
        self.numPiscinas = QtWidgets.QLineEdit(self.gridWidget)
        self.numPiscinas.setStyleSheet("border-radius: 5px; \n"
"color: white; ")
        self.numPiscinas.setObjectName("numPiscinas")
        self.gridLayout.addWidget(self.numPiscinas, 5, 1, 1, 1)
        self.nPeopleSpinBox = QtWidgets.QSpinBox(self.gridWidget)
        self.nPeopleSpinBox.setStyleSheet("font: 8pt \"Myanmar Text\";\n"
"border: none;\n"
"border-radius: 5px;\n"
"background-color: \"#329CE3\";")
        self.nPeopleSpinBox.setObjectName("nPeopleSpinBox")
        self.gridLayout.addWidget(self.nPeopleSpinBox, 2, 1, 1, 1)
        self.lower14 = QtWidgets.QLabel(self.gridWidget)
        self.lower14.setStyleSheet("font: 9pt \"Candara\";\n"
"border: none; ")
        self.lower14.setObjectName("lower14")
        self.gridLayout.addWidget(self.lower14, 4, 0, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.gridWidget)
        self.timeEdit.setStyleSheet("font: 8pt \"Myanmar Text\";\n"
"border-radius: 10px;\n"
"border: none;\n"
"background-color: \"#329CE3\";")
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 1, 1, 1, 1)
        self.lower14SpinBox = QtWidgets.QSpinBox(self.gridWidget)
        self.lower14SpinBox.setStyleSheet("font: 8pt \"Myanmar Text\";\n"
"border-radius: 5px;\n"
"border: none;\n"
"background-color: \"#329CE3\";\n"
"")
        self.lower14SpinBox.setObjectName("lower14SpinBox")
        self.gridLayout.addWidget(self.lower14SpinBox, 4, 1, 1, 1)
        self.grater70SpinBox = QtWidgets.QSpinBox(self.gridWidget)
        self.grater70SpinBox.setStyleSheet("font: 8pt \"Myanmar Text\";\n"
"border: none;\n"
"border-radius:  5px;\n"
"background-color: \"#329CE3\";\n"
"font-weight: bolder; ")
        self.grater70SpinBox.setObjectName("grater70SpinBox")
        self.gridLayout.addWidget(self.grater70SpinBox, 3, 1, 1, 1)
        self.cajitaError = QtWidgets.QLineEdit(self.gridWidget)
        self.cajitaError.setStyleSheet("border: none; ")
        self.cajitaError.setObjectName("cajitaError")
        self.gridLayout.addWidget(self.cajitaError, 0, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(130, 90, 351, 541))
        self.frame.setStyleSheet("background-color: \"#60ACE9\";\n"
"border-radius: 5px; ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.reservar = QtWidgets.QPushButton(self.frame)
        self.reservar.setGeometry(QtCore.QRect(100, 490, 75, 23))
        self.reservar.setStyleSheet("color: black; \n"
"border: 1px solid white; \n"
"background-color: white; ")
        self.reservar.setObjectName("reservar")
        self.atras = QtWidgets.QPushButton(self.frame)
        self.atras.setGeometry(QtCore.QRect(190, 490, 75, 23))
        self.atras.setStyleSheet("color: black; \n"
"border: 1px solid white; \n"
"background-color: white; ")
        self.atras.setObjectName("atras")
        self.frame.raise_()
        self.calendar.raise_()
        self.gridWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.greater70.setText(_translate("MainWindow", "Mayores de 70"))
        self.nPeople.setText(_translate("MainWindow", "Personas"))
        self.numPiscinasLabel.setText(_translate("MainWindow", "Número Piscina"))
        self.entryHour.setText(_translate("MainWindow", "Hora de entrada"))
        self.lower14.setText(_translate("MainWindow", "Menores de 14"))
        self.reservar.setText(_translate("MainWindow", "Reservar"))
        self.atras.setText(_translate("MainWindow", "Atrás"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowx()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
