# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\cancelarReserva.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindoww(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: \"#60ACE9\";\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(275, 90, 281, 41))
        self.textBrowser.setStyleSheet("color: white; \n"
"font: 75 10pt \"Candara\";\n"
"border-radius: 5px; \n"
"border: 1px solid \"#E0E0E0\";")
        self.textBrowser.setObjectName("textBrowser")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(330, 380, 156, 23))
        self.buttonBox.setStyleSheet("border-radius: 2px; \n"
"background-color: \"#E0E0E0\";\n"
"color: black; \n"
"padding: 0px 20px 0px 20px; ")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(220, 150, 391, 231))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.correoElectronicoLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.correoElectronicoLabel.setStyleSheet("color: white; \n"
"font: 75 10pt \"Candara\";")
        self.correoElectronicoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.correoElectronicoLabel.setObjectName("correoElectronicoLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.correoElectronicoLabel)
        self.dateEdit = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.dateEdit.setStyleSheet("border: 2px solid \"#E0E0E0\";\n"
"border-radius: 4px;\n"
"color: white; \n"
"align: center; ")
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.numContactLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.numContactLabel.setStyleSheet("color: white; \n"
"font: 75 10pt \"Candara\";")
        self.numContactLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numContactLabel.setObjectName("numContactLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.numContactLabel)
        self.numContactLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.numContactLineEdit.setStyleSheet("border-radius: 4px; \n"
"border: 2px solid \"#E0E0E0\";")
        self.numContactLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.numContactLineEdit.setObjectName("numContactLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.numContactLineEdit)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Candara\'; font-size:10pt; font-weight:72; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; color:#ffffff;\">Cancelación de reserva</span></p></body></html>"))
        self.correoElectronicoLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Fecha de la reserva</span></p></body></html>"))
        self.numContactLabel.setText(_translate("MainWindow", "<html><head/><body><p>Número de la piscina</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindoww()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
